### ISSUE TITLE
py systems lcm: `test_lcm_driven_loop` intermittently fails (just on Mac?)

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#10637]
@jamiesnape mentioned that on Python 2 on his Mac machine, `test_lcm_drive_loop` intermittently fails on c48f00781e77fddd127c62389d104c2c6cf3ab4d:

```
ERROR: test_lcm_driven_loop (lcm_test.TestSystemsLcm)
Duplicates the test logic in `lcm_driven_loop_test.cc`.
----------------------------------------------------------------------
Traceback (most recent call last):
  File "./bindings/pydrake/systems/test/lcm_test.py", line 231, in test_lcm_driven_loop
    self.assertTrue(np.allclose(log_t_expected, log_t))
  File "/usr/local/lib/python2.7/site-packages/numpy/core/numeric.py", line 2423, in allclose
    res = all(isclose(a, b, rtol=rtol, atol=atol, equal_nan=equal_nan))
  File "/usr/local/lib/python2.7/site-packages/numpy/core/numeric.py", line 2524, in isclose
    return within_tol(x, y, atol, rtol)
  File "/usr/local/lib/python2.7/site-packages/numpy/core/numeric.py", line 2510, in within_tol
    return less_equal(abs(x-y), atol + rtol * abs(y))
ValueError: operands could not be broadcast together with shapes (6,) (5,) 
```

Most likely, it's due to some small race condition with the `multiprocessing` setup.

One option is to set this test as flaky, just in case.

(N.B. I believe this does not relate #10443 .)

**Comment by EricCousineau-TRI** [comment]
Just ran this binary 100x on our `macsim` instance, 10.14, in serial, 'cause parallel would cause interference; did not encounter any issue:
```
(set -eux; for i in $(seq 100); do echo $i; bazel run //bindings/pydrake/systems:py/lcm_test; done; )
```

So it seems to be site-specific?

**Comment by EricCousineau-TRI** [comment]
Given that #11281 landed, going to close this for now.
