### ISSUE TITLE
py multibody: Mach-O can't find `WeldJoint<Expression>::DoCloneToScalar(MultibodyTree<AutoDiffXd> const&) const`

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#11673]
Slack discussion:
https://drakedevelopers.slack.com/archives/C270MN28G/p1560950426013200

Relevant acute failure on CI (for commit 50be4a3, PR #11633):
https://drake-cdash.csail.mit.edu/testDetails.php?test=29601668&build=1184162

```
/Users/mojave/workspace/mac-mojave-clang-bazel-nightly-python3-release/_bazel_mojave/0cb874fab74aec8d8f6c3bf0a8c1e29b/sandbox/darwin-sandbox/11809/execroot/drake/bazel-out/darwin-opt/bin/bindings/pydrake/multibody/py/plant_test.runfiles/drake/common/test_utilities/drake_py_unittest_main.py:7: DeprecationWarning: the imp module is deprecated in favour of importlib; see the module's documentation for alternative uses
  import imp
Traceback (most recent call last):
  File "/Users/mojave/workspace/mac-mojave-clang-bazel-nightly-python3-release/_bazel_mojave/0cb874fab74aec8d8f6c3bf0a8c1e29b/sandbox/darwin-sandbox/11809/execroot/drake/bazel-out/darwin-opt/bin/bindings/pydrake/multibody/py/plant_test.runfiles/drake/common/test_utilities/drake_py_unittest_main.py", line 61, in <module>
    module = imp.load_source(test_name, runfiles_test_filename)
  File "/usr/local/Cellar/python/3.7.3/Frameworks/Python.framework/Versions/3.7/lib/python3.7/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 696, in _load
  File "<frozen importlib._bootstrap>", line 677, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 728, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/Users/mojave/workspace/mac-mojave-clang-bazel-nightly-python3-release/_bazel_mojave/0cb874fab74aec8d8f6c3bf0a8c1e29b/sandbox/darwin-sandbox/11809/execroot/drake/bazel-out/darwin-opt/bin/bindings/pydrake/multibody/py/plant_test.runfiles/drake/bindings/pydrake/multibody/test/plant_test.py", line 10, in <module>
    from pydrake.multibody.tree import (
ImportError: dlopen(/Users/mojave/workspace/mac-mojave-clang-bazel-nightly-python3-release/_bazel_mojave/0cb874fab74aec8d8f6c3bf0a8c1e29b/sandbox/darwin-sandbox/11809/execroot/drake/bazel-out/darwin-opt/bin/bindings/pydrake/multibody/py/plant_test.runfiles/drake/bindings/pydrake/multibody/tree.so, 2): Symbol not found: __ZNK5drake9multibody9WeldJointINS_8symbolic10ExpressionEE15DoCloneToScalarERKNS0_8internal13MultibodyTreeIN5Eigen14AutoDiffScalarINS7_6MatrixIdLin1ELi1ELi0ELin1ELi1EEEEEEE
  Referenced from: /Users/mojave/workspace/mac-mojave-clang-bazel-nightly-python3-release/_bazel_mojave/0cb874fab74aec8d8f6c3bf0a8c1e29b/sandbox/darwin-sandbox/11809/execroot/drake/bazel-out/darwin-opt/bin/bindings/pydrake/multibody/py/plant_test.runfiles/drake/bindings/pydrake/multibody/tree.so
  Expected in: flat namespace
 in /Users/mojave/workspace/mac-mojave-clang-bazel-nightly-python3-release/_bazel_mojave/0cb874fab74aec8d8f6c3bf0a8c1e29b/sandbox/darwin-sandbox/11809/execroot/drake/bazel-out/darwin-opt/bin/bindings/pydrake/multibody/py/plant_test.runfiles/drake/bindings/pydrake/multibody/tree.so

//bindings/pydrake/multibody:py/plant_test                               FAILED in 0.7s

  /Users/mojave/workspace/mac-mojave-clang-bazel-nightly-python3-release/_bazel_mojave/0cb874fab74aec8d8f6c3bf0a8c1e29b/execroot/drake/bazel-out/darwin-opt/testlogs/bindings/pydrake/multibody/py/plant_test/test.log
```

Demangling the symbol:
```
$ c++filt -_ -t __ZNK5drake9multibody9WeldJointINS_8symbolic10ExpressionEE15DoCloneToScalarERKNS0_8internal13MultibodyTreeIN5Eigen14AutoDiffScalarINS7_6MatrixIdLin1ELi1ELi0ELin1ELi1EEEEEEE
drake::multibody::WeldJoint<drake::symbolic::Expression>::DoCloneToScalar(drake::multibody::internal::MultibodyTree<Eigen::AutoDiffScalar<Eigen::Matrix<double, -1, 1, 0, -1, 1> > > const&) const
```

@jwnimmer-tri's suggestions:

> jwnimmer-tri  [1 hour ago]
> The first thing I'd do is try adding `~WeldJoint() final;` to the header and a definition _in the cc file_ and see if that helps the Mach-O linker find its pants.
> 
> jwnimmer-tri  [1 hour ago]
> Having `const std::string& type_name() const override` as the lexically first virtual method in the header file have _an inline definition_ is playing with fire.
> 
> jwnimmer-tri  [1 hour ago]
> Oh gosh, and it has a `never_destroyed` in it.  Double fire. (edited)
> 
> jwnimmer-tri  [1 hour ago]
> So then the second thing I'd try is to move the `type_name` definition to the cc file.

Relates revert, #11672

\cc @ggould-tri @SeanCurtis-TRI @m-chaturvedi

**Comment by EricCousineau-TRI** [comment]
Er, it looks like the real culprit is that we just don't instantiate the weld joint for symbolic?
https://github.com/RobotLocomotion/drake/blob/8f87aabc46d8d750be4682457673dd8ffb99cf46/multibody/tree/weld_joint.cc#L62-L63

TBH, I have *no* idea why this was even passing on Linux???

**Comment by EricCousineau-TRI** [comment]
My guess is that Linux didn't fail because it used a sort of lazy symbol loading, while Mac used something more immediate?

**Comment by jwnimmer-tri** [comment]
The template could have been implicitly instantiated on Linux.  Just because the explicit instantiation was missing doesn't mean that the compiler is forbidden from implicitly instantiating it.  Or, the symbol was never used (inlined) on Linux but not macOS.  Or, ...

**Comment by EricCousineau-TRI** [comment]
Well, the definition itself isn't available in the header file... And applying this diff on top of 50be4a3 doesn't even generate an error, so I'm completely stumped:
```patch
diff --git a/bindings/pydrake/multibody/test/plant_test.py b/bindings/pydrake/multibody/test/plant_test.py
index 0eadc9229..cb07c6734 100644
--- a/bindings/pydrake/multibody/test/plant_test.py
+++ b/bindings/pydrake/multibody/test/plant_test.py
@@ -360,7 +360,12 @@ class TestPlant(unittest.TestCase):
             A=plant_f.world_frame(), B=plant_f.GetFrameByName("base"))
         plant_f.Finalize()
         plant = to_type(plant_f, T)
+        print("---")
         print(plant)
+        if T != AutoDiffXd:
+            print(plant.ToAutoDiffXd())
+        if T != Expression:
+            print(plant.ToSymbolic())
         return
 
         context = plant.CreateDefaultContext()
```

However, I'm insufficiently interested to dig any further :P

**Comment by jwnimmer-tri** [comment]
The implementation of `WeldJoint<double>::DoCloneToScalar(const internal::MultibodyTree<Expression>&) ` ends up doing `std::make_unique<WeldJoint<Expression>>` which implicitly instantiates `WeldJoint` on `Expression`.

**Comment by EricCousineau-TRI** [comment]
Ohhhhh, that makes sense. Thanks!
