### ISSUE TITLE
py systems: Should make make debug messages with NiceTypeName prettier for Python?

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#13237]
Issue-ifying #13194. [See discussion](https://github.com/RobotLocomotion/drake/pull/13194#pullrequestreview-403981032)

Motivated by the error encountered here:
https://stackoverflow.com/q/61506822/7829525

> The goal is to turn this message:
> ```
> Traceback (most recent call last):
>   File "debugging.py", line 24, in <module>
>     DirectTranscription(sys, sys.CreateDefaultContext(), 10)
> RuntimeError: The object named [] of type drake::pydrake::(anonymous)::Impl<double>::PyVectorSystem does not support ToAutoDiffXd.
> ```
> into this message:
> ```
> Traceback (most recent call last):
>   File "debugging.py", line 24, in <module>
>     DirectTranscription(sys, sys.CreateDefaultContext(), 10)
> RuntimeError: The object named [] of type my_module.CustomVectorSystem does not support ToAutoDiffXd.
> ```
> 
> The actual type name `drake::pydrake::(anonymous)::Impl<double>::PyVectorSystem` is rather uninformative (aside from being ugly) if you have a  diagram with multiple Python-authored systems that you're trying to convert. (They'll all look the same.)

\cc @sherm1 @jwnimmer-tri

**Comment by EricCousineau-TRI** [comment]
Came across some other kinda obtuse-looking errors:
https://stackoverflow.com/q/61600097/7829525

```
RuntimeError: Reported algebraic loop detected in DiagramBuilder:
  InputPort[0] (phi) of System ::drake/pydrake/(anonymous)/Impl@000000000648eec0 (Impl<double>::PyLeafSystemBase<drake::pydrake::(anonymous)::Impl<double>::LeafSystemPublic>) is direct-feedthrough to
  OutputPort[0] (Lam) of System ::drake/pydrake/(anonymous)/Impl@000000000648eec0 (Impl<double>::PyLeafSystemBase<drake::pydrake::(anonymous)::Impl<double>::LeafSystemPublic>) is connected to
  InputPort[0] (u0) of System ::drake/systems/BarycentricMeshSystem@0000000005c6d300 (BarycentricMeshSystem<double>) is direct-feedthrough to
  OutputPort[0] (y0) of System ::drake/systems/BarycentricMeshSystem@0000000005c6d300 (BarycentricMeshSystem<double>) is connected to
  InputPort[0] (phi) of System ::drake/pydrake/(anonymous)/Impl@000000000648eec0 (Impl<double>::PyLeafSystemBase<drake::pydrake::(anonymous)::Impl<double>::LeafSystemPublic>)
```

It's not a show-stopper by any means, but would be nice to see something a tad more coherent.
