### ISSUE TITLE
//bindings/pydrake/doc:gen_sphinx_test fails under Sphinx 3.1

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#13529]
```
 FAIL: //bindings/pydrake/doc:gen_sphinx_test (see /Users/catalina/workspace/mac-catalina-unprovisioned-clang-bazel-nightly-release/_bazel_catalina/a976cb703e3d4c795e57f0798a36e0fb/execroot/drake/bazel-out/darwin-opt/testlogs/bindings/pydrake/doc/gen_sphinx_test/test.log)
 INFO: From Testing //bindings/pydrake/doc:gen_sphinx_test:
 ==================== Test output for //bindings/pydrake/doc:gen_sphinx_test: 
 Traceback (most recent call last):
   File "/usr/local/lib/python3.8/site-packages/sphinx/cmd/build.py", line 280, in build_main
     app.build(args.force_all, filenames)
   File "/usr/local/lib/python3.8/site-packages/sphinx/application.py", line 342, in build
     self.builder.build_all()
   File "/usr/local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 260, in build_all
     self.build(None, summary=__('all source files'), method='all')
   File "/usr/local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 311, in build
     updated_docnames = set(self.read())
   File "/usr/local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 418, in read
     self._read_serial(docnames)
   File "/usr/local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 439, in _read_serial
     self.read_doc(docname)
   File "/usr/local/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 479, in read_doc
     doctree = read_doc(self.app, self.env, self.env.doc2path(docname))
   File "/usr/local/lib/python3.8/site-packages/sphinx/io.py", line 221, in read_doc
     pub.publish()
   File "/usr/local/lib/python3.8/site-packages/docutils/core.py", line 217, in publish
     self.document = self.reader.read(self.source, self.parser,
   File "/usr/local/lib/python3.8/site-packages/sphinx/io.py", line 126, in read
     self.parse()
   File "/usr/local/lib/python3.8/site-packages/docutils/readers/__init__.py", line 77, in parse
     self.parser.parse(self.input, document)
   File "/usr/local/lib/python3.8/site-packages/sphinx/parsers.py", line 102, in parse
     self.statemachine.run(inputlines, document, inliner=self.inliner)
   File "/usr/local/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 170, in run
     results = StateMachineWS.run(self, input_lines, input_offset,
   File "/usr/local/lib/python3.8/site-packages/docutils/statemachine.py", line 241, in run
     context, next_state, result = self.check_line(
   File "/usr/local/lib/python3.8/site-packages/docutils/statemachine.py", line 459, in check_line
     return method(match, context, next_state)
   File "/usr/local/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2769, in underline
     self.section(title, source, style, lineno - 1, messages)
   File "/usr/local/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 327, in section
     self.new_subsection(title, lineno, messages)
   File "/usr/local/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 393, in new_subsection
     newabsoffset = self.nested_parse(
   File "/usr/local/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 281, in nested_parse
     state_machine.run(block, input_offset, memo=self.memo,
   File "/usr/local/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 196, in run
     results = StateMachineWS.run(self, input_lines, input_offset)
   File "/usr/local/lib/python3.8/site-packages/docutils/statemachine.py", line 241, in run
     context, next_state, result = self.check_line(
   File "/usr/local/lib/python3.8/site-packages/docutils/statemachine.py", line 459, in check_line
     return method(match, context, next_state)
   File "/usr/local/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2342, in explicit_markup
     nodelist, blank_finish = self.explicit_construct(match)
   File "/usr/local/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2354, in explicit_construct
     return method(self, expmatch)
   File "/usr/local/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2096, in directive
     return self.run_directive(
   File "/usr/local/lib/python3.8/site-packages/docutils/parsers/rst/states.py", line 2146, in run_directive
     result = directive_instance.run()
   File "/usr/local/lib/python3.8/site-packages/sphinx/ext/autodoc/directive.py", line 146, in run
     documenter.generate(more_content=self.content)
   File "/usr/local/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 842, in generate
     self.document_members(all_members)
   File "/Users/catalina/workspace/mac-catalina-unprovisioned-clang-bazel-nightly-release/_bazel_catalina/a976cb703e3d4c795e57f0798a36e0fb/sandbox/darwin-sandbox/11566/execroot/drake/bazel-out/darwin-opt/bin/bindings/pydrake/doc/gen_sphinx_test.runfiles/drake/bindings/pydrake/doc/pydrake_sphinx_extension.py", line 38, in method
     return f(original, *args, **kwargs)
   File "/Users/catalina/workspace/mac-catalina-unprovisioned-clang-bazel-nightly-release/_bazel_catalina/a976cb703e3d4c795e57f0798a36e0fb/sandbox/darwin-sandbox/11566/execroot/drake/bazel-out/darwin-opt/bin/bindings/pydrake/doc/gen_sphinx_test.runfiles/drake/bindings/pydrake/doc/pydrake_sphinx_extension.py", line 350, in patch_document_members
     documenter.generate(
   File "/usr/local/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 1520, in generate
     return super().generate(more_content=more_content,
   File "/usr/local/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 829, in generate
     sig = self.format_signature()
   File "/usr/local/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 1398, in format_signature
     sig = super().format_signature()
   File "/usr/local/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 1119, in format_signature
     result = self._find_signature()
   File "/usr/local/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py", line 1072, in _find_signature
     match = py_ext_sig_re.match(line)
   File "/Users/catalina/workspace/mac-catalina-unprovisioned-clang-bazel-nightly-release/_bazel_catalina/a976cb703e3d4c795e57f0798a36e0fb/sandbox/darwin-sandbox/11566/execroot/drake/bazel-out/darwin-opt/bin/bindings/pydrake/doc/gen_sphinx_test.runfiles/drake/bindings/pydrake/doc/pydrake_sphinx_extension.py", line 109, in match
     pieces = repair_naive_name_split(symbol.split('.'))
   File "/Users/catalina/workspace/mac-catalina-unprovisioned-clang-bazel-nightly-release/_bazel_catalina/a976cb703e3d4c795e57f0798a36e0fb/sandbox/darwin-sandbox/11566/execroot/drake/bazel-out/darwin-opt/bin/bindings/pydrake/doc/gen_sphinx_test.runfiles/drake/bindings/pydrake/doc/pydrake_sphinx_extension.py", line 51, in repair_naive_name_split
     assert num_open >= 0
 AssertionError
 Exception occurred:
   File "/Users/catalina/workspace/mac-catalina-unprovisioned-clang-bazel-nightly-release/_bazel_catalina/a976cb703e3d4c795e57f0798a36e0fb/sandbox/darwin-sandbox/11566/execroot/drake/bazel-out/darwin-opt/bin/bindings/pydrake/doc/gen_sphinx_test.runfiles/drake/bindings/pydrake/doc/pydrake_sphinx_extension.py", line 51, in repair_naive_name_split
     assert num_open >= 0
 AssertionError
 The full traceback has been saved in /var/folders/61/c4s50nsd2kd9fvpxk4t8zd940000gn/T/sphinx-err-iwkps37_.log, if you want to report the issue to the developers.
 Please also report this if it was a user error, so that a better error message can be provided next time.
 A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
 Generating documentation...
 Traceback (most recent call last):
   File "/Users/catalina/workspace/mac-catalina-unprovisioned-clang-bazel-nightly-release/_bazel_catalina/a976cb703e3d4c795e57f0798a36e0fb/sandbox/darwin-sandbox/11566/execroot/drake/bazel-out/darwin-opt/bin/bindings/pydrake/doc/gen_sphinx_test.runfiles/drake/bindings/pydrake/doc/gen_sphinx.py", line 118, in <module>
     main()
   File "/Users/catalina/workspace/mac-catalina-unprovisioned-clang-bazel-nightly-release/_bazel_catalina/a976cb703e3d4c795e57f0798a36e0fb/sandbox/darwin-sandbox/11566/execroot/drake/bazel-out/darwin-opt/bin/bindings/pydrake/doc/gen_sphinx_test.runfiles/drake/bindings/pydrake/doc/gen_sphinx.py", line 110, in main
     gen_main(
   File "/Users/catalina/workspace/mac-catalina-unprovisioned-clang-bazel-nightly-release/_bazel_catalina/a976cb703e3d4c795e57f0798a36e0fb/sandbox/darwin-sandbox/11566/execroot/drake/bazel-out/darwin-opt/bin/bindings/pydrake/doc/gen_sphinx_test.runfiles/drake/doc/sphinx_base.py", line 66, in gen_main
     check_call([
   File "/usr/local/Cellar/python@3.8/3.8.3/Frameworks/Python.framework/Versions/3.8/lib/python3.8/subprocess.py", line 364, in check_call
     raise CalledProcessError(retcode, cmd)
 subprocess.CalledProcessError: Command '['/usr/local/opt/python@3.8/bin/python3.8', 'doc/sphinx_build.py', '-b', 'html', '-a', '-E', '-d', '/Users/catalina/workspace/mac-catalina-unprovisioned-clang-bazel-nightly-release/_bazel_catalina/a976cb703e3d4c795e57f0798a36e0fb/sandbox/darwin-sandbox/11566/execroot/drake/_tmp/e9a2f7ea99ae93a4847f6e2a13109812/tmp613o6er0/doctrees', '-N', '-Q', '-T', '/Users/catalina/workspace/mac-catalina-unprovisioned-clang-bazel-nightly-release/_bazel_catalina/a976cb703e3d4c795e57f0798a36e0fb/sandbox/darwin-sandbox/11566/execroot/drake/_tmp/e9a2f7ea99ae93a4847f6e2a13109812/tmp613o6er0/src', '/Users/catalina/workspace/mac-catalina-unprovisioned-clang-bazel-nightly-release/_bazel_catalina/a976cb703e3d4c795e57f0798a36e0fb/sandbox/darwin-sandbox/11566/execroot/drake/_tmp/e9a2f7ea99ae93a4847f6e2a13109812/doc']' returned non-zero exit status 2.
================================================================================
```

**Comment by jwnimmer-tri** [comment]
Per f2f: easiest path might be to just use (or fork) the homebrew formula.

**Comment by jamiesnape** [comment]
https://github.com/RobotLocomotion/homebrew-director/commit/7e09f48b93ea4505a51455fd68e8f0ff6834031c is part of the solution.
