### ISSUE TITLE
pip install: 

### ISSUE THREAD

**Issue by BetsyMcPhail** [RobotLocomotion/drake#15730]
Working towards #1183 

Spin-off of issue found in #15633 

```
python3 -c 'import pydrake.all'
Traceback (most recent call last):
  File "/usr/local/lib/python3.6/dist-packages/pydrake/manipulation/simple_ui.py", line 7, in <module>
    import tkinter as tk
ModuleNotFoundError: No module named 'tkinter'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/usr/local/lib/python3.6/dist-packages/pydrake/all.py", line 48, in <module>
    from .manipulation.all import *
  File "/usr/local/lib/python3.6/dist-packages/pydrake/manipulation/all.py", line 4, in <module>
    from .simple_ui import *
  File "/usr/local/lib/python3.6/dist-packages/pydrake/manipulation/simple_ui.py", line 9, in <module>
    import Tkinter as tk
ModuleNotFoundError: No module named 'Tkinter'
```

I tried to manually install the missing package:

`sudo apt-get install python3-tk`

An moved passed the error:

```
root@94aa8068945d:/wheel/dist# python3 -c 'import pydrake.all'
root@94aa8068945d:/wheel/dist#
```

[It appears](https://tkdocs.com/tutorial/install.html) that this will not be in issue in Python 3.7+, however may be something to consider in Python 3.6

**Comment by jwnimmer-tri** [comment]
It's probable that #14702 is the best long-term fix for this problem.  Whether it's also the best short-term fix is TBD.

Note that there are three files that use `tk`.

Maybe y'all can start trying to do the replacement, and see how difficult it might be.
