### ISSUE TITLE
[ci] "FlowNode was not found in storage for head id:FlowNodeId [...]"

### ISSUE THREAD

**Issue by EricCousineau-TRI** [RobotLocomotion/drake#19859]
Failures on CI
https://drakedevelopers.slack.com/archives/C270MN28G/p1690470200151389

Initial occurrences:
https://drake-jenkins.csail.mit.edu/view/Production/job/mac-x86-monterey-unprovisioned-clang-wheel-nightly-release/143/
https://drake-jenkins.csail.mit.edu/view/Production/job/mac-x86-monterey-unprovisioned-clang-bazel-nightly-packaging/160/
https://drake-jenkins.csail.mit.edu/view/Production/job/linux-focal-unprovisioned-gcc-wheel-nightly-release/147/ - `FlowNode was not found in storage for head id:FlowNodeId [...]`

Assigning @jwnimmer-tri for disposition, \cc @BetsyMcPhail

**Comment by jwnimmer-tri** [comment]
Best guess, maybe the Jenkins master restarted?

**Comment by svenevs** [comment]
Added some logging information below, possibly `Found incomplete build with completed execution - display name: linux-focal-unprovisioned-gcc-wheel-nightly-release #147` indicates something, but there doesn't seem to be much actionable information on this online.  Jenkins ticket [discussing some relevant details](https://issues.jenkins.io/browse/JENKINS-55287).  There's mention:

> The PERFORMANCE_OPTIMIZED durability level makes no guarantees that Pipelines will be resumable if Jenkins crashes, so this behavior is expected in that case. There is supposed to be a more user-friendly error message explaining that the Pipeline cannot be resumed for these reasons rather than just the raw error of what exactly kept the Pipeline from resuming, but that is broken because of [JENKINS-53358](https://issues.jenkins.io/browse/JENKINS-53358).

So if we start to see this more, then we probably want to change the [speed durability](https://jenkins-job-builder.readthedocs.io/en/latest/properties.html#properties.speed-durability) in our jenkins yaml?

```yaml
properties:
  - speed-durability:
      hint: performance-optimized  # or survivable-non-atomic, max-survivability
```

Developer note about the jenkins log (to find things more easily...), it's in UTC time, choose the url `143/consoleText` (not `/consoleFull`) to get `[2023-07-27T05:44:38.906Z] [3,232 / 5,052] Compiling src/common_robotics_utilities/math.cpp; 21s darwin-sandbox ... (4 actions running)` for example.

To me, this seems like a fluke.  Maybe a restart, maybe jenkins was overloaded and dropped something, network error?  :crossed_fingers: 

```
2023-07-27 05:58:58.045+0000 [id=97]    INFO    o.j.p.g.GhprbTrigger$StartHookRunnable#run: Created hook for RobotLocomotion/drake
2023-07-27 05:58:58.290+0000 [id=31]    INFO    h.p.ec2.EC2RetentionStrategy#internalCheck: Startup timeout of EC2 (us-east-1) - drake-linux-focal-unprovisioned-2023-07-10 (i-01664752ff10b4afb) after 3529289 milliseconds (timeout: 300000 milliseconds), insta
nce status: RUNNING
2023-07-27 05:58:58.290+0000 [id=31]    INFO    h.plugins.ec2.EC2AbstractSlave#launchTimeout: EC2 instance failed to launch: i-01664752ff10b4afb
2023-07-27 05:58:58.292+0000 [id=31]    WARNING hudson.model.AbstractCIBase#updateComputer: Node test-mac-provisioned-m1-config has no executors. Cannot update the Computer instance of it
2023-07-27 05:58:58.345+0000 [id=96]    INFO    o.j.p.g.GhprbTrigger$StartHookRunnable#run: Created hook for RobotLocomotion/drake
2023-07-27 05:58:58.393+0000 [id=31]    WARNING o.j.p.w.cps.CpsFlowExecution#onLoad: Error initializing storage and loading nodes, will try to create placeholders for: CpsFlowExecution[Owner[linux-focal-unprovisioned-gcc-wheel-nightly-release/147:linux-focal
-unprovisioned-gcc-wheel-nightly-release #147]]
java.io.IOException: Tried to load head FlowNodes for execution Owner[linux-focal-unprovisioned-gcc-wheel-nightly-release/147:linux-focal-unprovisioned-gcc-wheel-nightly-release #147] but FlowNode was not found in storage for head id:FlowNodeId 1:27
        at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.initializeStorage(CpsFlowExecution.java:689)
        at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.onLoad(CpsFlowExecution.java:726)
        at org.jenkinsci.plugins.workflow.job.WorkflowRun.getExecution(WorkflowRun.java:691)
        at org.jenkinsci.plugins.workflow.job.WorkflowRun.onLoad(WorkflowRun.java:550)
        at hudson.model.RunMap.retrieve(RunMap.java:226)
        at hudson.model.RunMap.retrieve(RunMap.java:57)
        at jenkins.model.lazy.AbstractLazyLoadRunMap.load(AbstractLazyLoadRunMap.java:501)
        at jenkins.model.lazy.AbstractLazyLoadRunMap.load(AbstractLazyLoadRunMap.java:483)
        at jenkins.model.lazy.AbstractLazyLoadRunMap.getByNumber(AbstractLazyLoadRunMap.java:381)
        at hudson.model.RunMap.getById(RunMap.java:206)
        at org.jenkinsci.plugins.workflow.job.WorkflowRun$Owner.run(WorkflowRun.java:940)
        at org.jenkinsci.plugins.workflow.job.WorkflowRun$Owner.get(WorkflowRun.java:951)
        at org.jenkinsci.plugins.workflow.flow.FlowExecutionList$1.computeNext(FlowExecutionList.java:65)
        at org.jenkinsci.plugins.workflow.flow.FlowExecutionList$1.computeNext(FlowExecutionList.java:57)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
        at org.jenkinsci.plugins.workflow.flow.FlowExecutionList$ItemListenerImpl.onLoaded(FlowExecutionList.java:178)
        at jenkins.model.Jenkins.<init>(Jenkins.java:1013)
        at hudson.model.Hudson.<init>(Hudson.java:86)
        at hudson.model.Hudson.<init>(Hudson.java:82)
        at hudson.WebAppMain$3.run(WebAppMain.java:295)
2023-07-27 05:58:58.395+0000 [id=31]    INFO    o.j.p.w.cps.CpsFlowExecution#createPlaceholderNodes: Creating placeholder flownodes for execution: CpsFlowExecution[Owner[linux-focal-unprovisioned-gcc-wheel-nightly-release/147:linux-focal-unprovisioned-gcc-wh
eel-nightly-release #147]]
2023-07-27 05:58:58.443+0000 [id=31]    WARNING o.j.p.workflow.job.WorkflowRun#getExecution: Found incomplete build with completed execution - display name: linux-focal-unprovisioned-gcc-wheel-nightly-release #147
2023-07-27 05:58:58.463+0000 [id=31]    WARNING o.j.p.w.cps.CpsFlowExecution#onLoad: Error initializing storage and loading nodes, will try to create placeholders for: CpsFlowExecution[Owner[mac-x86-monterey-unprovisioned-clang-bazel-nightly-packaging/160:ma
c-x86-monterey-unprovisioned-clang-bazel-nightly-packaging #160]]
java.io.IOException: Tried to load head FlowNodes for execution Owner[mac-x86-monterey-unprovisioned-clang-bazel-nightly-packaging/160:mac-x86-monterey-unprovisioned-clang-bazel-nightly-packaging #160] but FlowNode was not found in storage for head id:FlowNo
deId 1:27
        at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.initializeStorage(CpsFlowExecution.java:689)
        at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.onLoad(CpsFlowExecution.java:726)
        at org.jenkinsci.plugins.workflow.job.WorkflowRun.getExecution(WorkflowRun.java:691)
        at org.jenkinsci.plugins.workflow.job.WorkflowRun.onLoad(WorkflowRun.java:550)
        at hudson.model.RunMap.retrieve(RunMap.java:226)
        at hudson.model.RunMap.retrieve(RunMap.java:57)
        at jenkins.model.lazy.AbstractLazyLoadRunMap.load(AbstractLazyLoadRunMap.java:501)
        at jenkins.model.lazy.AbstractLazyLoadRunMap.load(AbstractLazyLoadRunMap.java:483)
        at jenkins.model.lazy.AbstractLazyLoadRunMap.getByNumber(AbstractLazyLoadRunMap.java:381)
        at hudson.model.RunMap.getById(RunMap.java:206)
        at org.jenkinsci.plugins.workflow.job.WorkflowRun$Owner.run(WorkflowRun.java:940)
        at org.jenkinsci.plugins.workflow.job.WorkflowRun$Owner.get(WorkflowRun.java:951)
        at org.jenkinsci.plugins.workflow.flow.FlowExecutionList$1.computeNext(FlowExecutionList.java:65)
        at org.jenkinsci.plugins.workflow.flow.FlowExecutionList$1.computeNext(FlowExecutionList.java:57)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
        at org.jenkinsci.plugins.workflow.flow.FlowExecutionList$ItemListenerImpl.onLoaded(FlowExecutionList.java:178)
        at jenkins.model.Jenkins.<init>(Jenkins.java:1013)
        at hudson.model.Hudson.<init>(Hudson.java:86)
        at hudson.model.Hudson.<init>(Hudson.java:82)
        at hudson.WebAppMain$3.run(WebAppMain.java:295)
2023-07-27 05:58:58.463+0000 [id=31]    INFO    o.j.p.w.cps.CpsFlowExecution#createPlaceholderNodes: Creating placeholder flownodes for execution: CpsFlowExecution[Owner[mac-x86-monterey-unprovisioned-clang-bazel-nightly-packaging/160:mac-x86-monterey-unprov
isioned-clang-bazel-nightly-packaging #160]]
2023-07-27 05:58:58.468+0000 [id=31]    WARNING o.j.p.workflow.job.WorkflowRun#getExecution: Found incomplete build with completed execution - display name: mac-x86-monterey-unprovisioned-clang-bazel-nightly-packaging #160
2023-07-27 05:58:58.473+0000 [id=31]    WARNING o.j.p.w.cps.CpsFlowExecution#onLoad: Error initializing storage and loading nodes, will try to create placeholders for: CpsFlowExecution[Owner[mac-x86-monterey-unprovisioned-clang-wheel-nightly-release/143:mac-
x86-monterey-unprovisioned-clang-wheel-nightly-release #143]]
java.io.IOException: Tried to load head FlowNodes for execution Owner[mac-x86-monterey-unprovisioned-clang-wheel-nightly-release/143:mac-x86-monterey-unprovisioned-clang-wheel-nightly-release #143] but FlowNode was not found in storage for head id:FlowNodeId
 1:27
        at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.initializeStorage(CpsFlowExecution.java:689)
        at org.jenkinsci.plugins.workflow.cps.CpsFlowExecution.onLoad(CpsFlowExecution.java:726)
        at org.jenkinsci.plugins.workflow.job.WorkflowRun.getExecution(WorkflowRun.java:691)
        at org.jenkinsci.plugins.workflow.job.WorkflowRun.onLoad(WorkflowRun.java:550)
        at hudson.model.RunMap.retrieve(RunMap.java:226)
        at hudson.model.RunMap.retrieve(RunMap.java:57)
        at jenkins.model.lazy.AbstractLazyLoadRunMap.load(AbstractLazyLoadRunMap.java:501)
        at jenkins.model.lazy.AbstractLazyLoadRunMap.load(AbstractLazyLoadRunMap.java:483)
        at jenkins.model.lazy.AbstractLazyLoadRunMap.getByNumber(AbstractLazyLoadRunMap.java:381)
        at hudson.model.RunMap.getById(RunMap.java:206)
        at org.jenkinsci.plugins.workflow.job.WorkflowRun$Owner.run(WorkflowRun.java:940)
        at org.jenkinsci.plugins.workflow.job.WorkflowRun$Owner.get(WorkflowRun.java:951)
        at org.jenkinsci.plugins.workflow.flow.FlowExecutionList$1.computeNext(FlowExecutionList.java:65)
        at org.jenkinsci.plugins.workflow.flow.FlowExecutionList$1.computeNext(FlowExecutionList.java:57)
        at com.google.common.collect.AbstractIterator.tryToComputeNext(AbstractIterator.java:143)
        at com.google.common.collect.AbstractIterator.hasNext(AbstractIterator.java:138)
        at org.jenkinsci.plugins.workflow.flow.FlowExecutionList$ItemListenerImpl.onLoaded(FlowExecutionList.java:178)
        at jenkins.model.Jenkins.<init>(Jenkins.java:1013)
        at hudson.model.Hudson.<init>(Hudson.java:86)
        at hudson.model.Hudson.<init>(Hudson.java:82)
        at hudson.WebAppMain$3.run(WebAppMain.java:295)
2023-07-27 05:58:58.473+0000 [id=31]    INFO    o.j.p.w.cps.CpsFlowExecution#createPlaceholderNodes: Creating placeholder flownodes for execution: CpsFlowExecution[Owner[mac-x86-monterey-unprovisioned-clang-wheel-nightly-release/143:mac-x86-monterey-unprovis
ioned-clang-wheel-nightly-release #143]]
2023-07-27 05:58:58.477+0000 [id=31]    WARNING o.j.p.workflow.job.WorkflowRun#getExecution: Found incomplete build with completed execution - display name: mac-x86-monterey-unprovisioned-clang-wheel-nightly-release #143
2023-07-27 05:58:58.479+0000 [id=31]    INFO    hudson.WebAppMain$3#run: Jenkins is fully up and running
2023-07-27 05:58:58.541+0000 [id=124]   INFO    h.plugins.ec2.EC2OndemandSlave#lambda$terminate$0: Terminated EC2 instance (terminated): i-01664752ff10b4afb
2023-07-27 05:58:58.543+0000 [id=124]   WARNING hudson.model.AbstractCIBase#updateComputer: Node test-mac-provisioned-m1-config has no executors. Cannot update the Computer instance of it
2023-07-27 05:58:58.550+0000 [id=124]   INFO    h.plugins.ec2.EC2OndemandSlave#lambda$terminate$0: Removed EC2 instance from jenkins controller: i-01664752ff10b4afb
2023-07-27 05:58:58.642+0000 [id=97]    INFO    o.j.p.g.GhprbTrigger$StartHookRunnable#run: Created hook for RobotLocomotion/drake
2023-07-27 05:58:58.904+0000 [id=99]    INFO    o.j.p.g.GhprbTrigger$StartHookRunnable#run: Created hook for RobotLocomotion/drake
2023-07-27 05:58:59.145+0000 [id=98]    INFO    o.j.p.g.GhprbTrigger$StartHookRunnable#run: Created hook for RobotLocomotion/drake
2023-07-27 05:58:59.424+0000 [id=94]    INFO    o.j.p.g.GhprbTrigger$StartHookRunnable#run: Created hook for RobotLocomotion/drake
2023-07-27 05:58:59.443+0000 [id=80]    INFO    o.j.p.workflow.job.WorkflowRun#finish: linux-focal-unprovisioned-gcc-wheel-nightly-release #147 completed: FAILURE
2023-07-27 05:58:59.466+0000 [id=75]    INFO    o.j.p.workflow.job.WorkflowRun#finish: mac-x86-monterey-unprovisioned-clang-bazel-nightly-packaging #160 completed: FAILURE
2023-07-27 05:58:59.475+0000 [id=108]   INFO    o.j.p.workflow.job.WorkflowRun#finish: mac-x86-monterey-unprovisioned-clang-wheel-nightly-release #143 completed: FAILURE
2023-07-27 05:58:59.484+0000 [id=80]    WARNING h.model.listeners.RunListener#report: RunListener failed
java.lang.StringIndexOutOfBoundsException: String index out of range: -16322
        at java.lang.String.checkBounds(String.java:381)
        at java.lang.String.<init>(String.java:462)
        at hudson.plugins.ansicolor.action.ShortlogActionCreator.findLastActionBefore(ShortlogActionCreator.java:70)
        at hudson.plugins.ansicolor.action.ShortlogActionCreator.createActionForShortlog(ShortlogActionCreator.java:39)
        at hudson.plugins.ansicolor.action.ShortlogActionCreator$Listener.onCompleted(ShortlogActionCreator.java:141)
        at hudson.model.listeners.RunListener.fireCompleted(RunListener.java:209)
        at org.jenkinsci.plugins.workflow.job.WorkflowRun.finish(WorkflowRun.java:617)
        at org.jenkinsci.plugins.workflow.job.WorkflowRun.access$800(WorkflowRun.java:137)
        at org.jenkinsci.plugins.workflow.job.WorkflowRun$FailOnLoadListener.lambda$onNewHead$0(WorkflowRun.java:1022)
        at jenkins.security.ImpersonatingScheduledExecutorService$1.run(ImpersonatingScheduledExecutorService.java:67)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$201(ScheduledThreadPoolExecutor.java:180)
        at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
        at java.lang.Thread.run(Thread.java:750)
2023-07-27 05:58:59.594+0000 [id=108]   WARNING o.j.p.w.flow.FlowExecutionList#unregister: Owner[mac-x86-monterey-unprovisioned-clang-wheel-nightly-release/143:mac-x86-monterey-unprovisioned-clang-wheel-nightly-release #143] was not in the list to begin with
: []
2023-07-27 05:58:59.595+0000 [id=80]    WARNING o.j.p.w.flow.FlowExecutionList#unregister: Owner[linux-focal-unprovisioned-gcc-wheel-nightly-release/147:linux-focal-unprovisioned-gcc-wheel-nightly-release #147] was not in the list to begin with: []
2023-07-27 05:58:59.595+0000 [id=75]    WARNING o.j.p.w.flow.FlowExecutionList#unregister: Owner[mac-x86-monterey-unprovisioned-clang-bazel-nightly-packaging/160:mac-x86-monterey-unprovisioned-clang-bazel-nightly-packaging #160] was not in the list to begin 
with: []
```

**Comment by jwnimmer-tri** [comment]
Closing as fluke.
