### ISSUE TITLE
pydrake_common_install_test fails with `ImportError: libgurobi70.so: cannot open shared object file`

### ISSUE THREAD

**Issue by RussTedrake** [RobotLocomotion/drake#7408]
Ubuntu 16.04, fresh update from master, and reran install_prereqs.sh to be sure.
I believe my GUROBI_PATH to be set correctly (and the other tests pass)

Output is extremely verbose, but ends with
```
[Installing] lib/libprotobuf_lite.a
[Installing] lib/libprotobuf_lite.so
[Installing] lib/libprotoc_lib.a
[Installing] lib/libprotoc_lib.so
[Installing] bin/protoc
[Installing] share/doc/drake/LICENSE.TXT
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/home/russt/.cache/bazel/_bazel_russt/fee0ea1b9d6c599156f0d1f0dd11b82e/bazel-sandbox/8213634680977329309/execroot/drake/bazel-out/clang-3.9-linux-opt/bin/drake/bindings/pydrake_common_install_test.runfiles/drake/tmp/lib/python2.7/site-packages/pydrake/__init__.py", line 7, in <module>
    from . import common
  File "/home/russt/.cache/bazel/_bazel_russt/fee0ea1b9d6c599156f0d1f0dd11b82e/bazel-sandbox/8213634680977329309/execroot/drake/bazel-out/clang-3.9-linux-opt/bin/drake/bindings/pydrake_common_install_test.runfiles/drake/tmp/lib/python2.7/site-packages/pydrake/common.py", line 3, in <module>
    from ._pydrake_common import *
ImportError: libgurobi70.so: cannot open shared object file: No such file or directory
E
======================================================================
ERROR: testDrakeFindResourceOrThrowInInstall (__main__.TestCommonInstall)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/russt/.cache/bazel/_bazel_russt/fee0ea1b9d6c599156f0d1f0dd11b82e/bazel-sandbox/8213634680977329309/execroot/drake/bazel-out/clang-3.9-linux-opt/bin/drake/bindings/pydrake_common_install_test.runfiles/drake/drake/bindings/python/pydrake/test/testCommonInstall.py", line 52, in testDrakeFindResourceOrThrowInInstall
  File "/usr/lib/python2.7/subprocess.py", line 574, in check_output
    raise CalledProcessError(retcode, cmd, output=output)
CalledProcessError: Command '['python2', '-c', 'import pydrake; print(pydrake.getDrakePath())']' returned non-zero exit status 1

----------------------------------------------------------------------
Ran 1 test in 2.176s

FAILED (errors=1)
================================================================================
INFO: Elapsed time: 5.623s, Critical Path: 3.13s
INFO: Build completed, 1 test FAILED, 3 total actions
//drake/bindings:pydrake_common_install_test                             FAILED in 3.1s
  /home/russt/.cache/bazel/_bazel_russt/fee0ea1b9d6c599156f0d1f0dd11b82e/execroot/drake/bazel-out/clang-3.9-linux-opt/testlogs/drake/bindings/pydrake_common_install_test/test.log

Executed 2 out of 2676 tests: 2675 tests pass and 1 fails locally.
```

Probably related to #6766, #6771 or #6772?

**Comment by EricCousineau-TRI** [comment]
I believe this has been solved by Jamie's https://github.com/RobotLocomotion/drake/pull/7873. Closing.
