### ISSUE TITLE
cpp_template_pybind_test fails with Apple LLVM compiler 10.0.0

### ISSUE THREAD

**Issue by jamiesnape** [RobotLocomotion/drake#9479]
Both on High Sierra and Mojave.

```
FAIL: //bindings/pydrake/util:py/cpp_template_pybind_test (see /private/var/tmp/_bazel_user/7c7ad393d9017d670ea6cd4ae3566d69/execroot/drake/bazel-out/darwin-opt/testlogs/bindings/pydrake/util/py/cpp_template_pybind_test/test.log)
INFO: From Testing //bindings/pydrake/util:py/cpp_template_pybind_test:
==================== Test output for //bindings/pydrake/util:py/cpp_template_pybind_test:
[==========] Running 3 tests from 1 test case.
[----------] Global test environment set-up.
[----------] 3 tests from CppTemplateTest
[ RUN      ] CppTemplateTest.TemplateClass
bindings/pydrake/util/test/cpp_template_pybind_test.cc:68: Failure
matcher(err.what(), R"([\s\S]*incompatible function arguments[\s\S]*\(arg0: __main__\.SimpleTemplate\[int\]\)[\s\S]*)") evaluates to false, where
err.what() evaluates to TypeError: simple_func(): incompatible function arguments. The following argument types are supported:
    1. (arg0: __main__.SimpleTemplate[int]) -> None

Invoked with: 'incorrect value'

At:
  <string>(2): <module>

R"([\s\S]*incompatible function arguments[\s\S]*\(arg0: __main__\.SimpleTemplate\[int\]\)[\s\S]*)" evaluates to [\s\S]*incompatible function arguments[\s\S]*\(arg0: __main__\.SimpleTemplate\[int\]\)[\s\S]*
[  FAILED  ] CppTemplateTest.TemplateClass (313 ms)
[ RUN      ] CppTemplateTest.TemplateFunction
[       OK ] CppTemplateTest.TemplateFunction (1 ms)
[ RUN      ] CppTemplateTest.TemplateMethod
[       OK ] CppTemplateTest.TemplateMethod (0 ms)
[----------] 3 tests from CppTemplateTest (314 ms total)

[----------] Global test environment tear-down
[==========] 3 tests from 1 test case ran. (314 ms total)
[  PASSED  ] 2 tests.
[  FAILED  ] 1 test, listed below:
[  FAILED  ] CppTemplateTest.TemplateClass

 1 FAILED TEST
Traceback (most recent call last):
  File "/private/var/tmp/_bazel_user/7c7ad393d9017d670ea6cd4ae3566d69/sandbox/darwin-sandbox/1749/execroot/drake/bazel-out/darwin-opt/bin/bindings/pydrake/util/py/cpp_template_pybind_test.runfiles/drake/tools/skylark/py_env_runner.py", line 13, in <module>
    subprocess.check_call(sys.argv[1:])
  File "/usr/local/Cellar/python@2/2.7.15_1/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 190, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['bindings/pydrake/util/cpp_template_pybind_test_cc']' returned non-zero exit status 1
```

**Comment by EricCousineau-TRI** [comment]
Seems like C++ STL's implementation of `std::regex` may differ from everything else?

The string that it outputs above should match?
`err.what()`:
```
TypeError: simple_func(): incompatible function arguments. The following argument types are supported:
    1. (arg0: __main__.SimpleTemplate[int]) -> None

Invoked with: 'incorrect value'

At:
  <string>(2): <module>
```

`regex`:
```
[\s\S]*incompatible function arguments[\s\S]*\(arg0: __main__\.SimpleTemplate\[int\]\)[\s\S]*
```
